linters:
  disable-all: false
  disable:
    - thelper
    - varnamelen
    - tagliatelle
    - wrapcheck
    - typecheck
  errcheck:
    exclude-functions:
      - fmt:.*
      - io/ioutil:^Read.*
      - github.com/spf13/cobra:MarkFlagRequired
      - github.com/spf13/viper:BindPFlag
linters-settings:
  gocyclo:
    min-complexity: 11
  golint:
    min-confidence: 1.1
issues:
  exclude:
    - composite
    - 'SA1019: "golang.org/x/crypto/ripemd160" is deprecated:' # Exclude deprecated ripemd160 warning
run:
  tests: false
