package minitia

import (
	"html/template"
	"os"
	"path/filepath"
	"strings"

	"github.com/initia-labs/weave/common"
)

// Create a simple data structure for the template
type RollyticsData struct {
	ChainID string
	VMType  string
}

func createRollyticsConfig(state LaunchState) error {
	// Define the template for .env file
	const configTemplate = `# Rollytics Configuration
# Generated by weave

# Database Configuration
DB_DSN=postgres://user:password@localhost:5431/rollytics?sslmode=disable
DB_AUTO_MIGRATE=true
# DB_MAX_CONNS=0                    # default: 0 (unlimited)
# DB_IDLE_CONNS=2                   # default: 2
# DB_BATCH_SIZE=100                 # default: 100

# Chain Configuration
CHAIN_ID={{.ChainID}}
VM_TYPE={{.VMType | lower}}
REST_URL=http://host.docker.internal:1317
RPC_URL=http://host.docker.internal:26657
JSON_RPC_URL=http://host.docker.internal:8545
# ACCOUNT_ADDRESS_PREFIX=init       # default: init

# Server Configuration
PORT=8088
LOG_LEVEL=info

# SENTRY_DSN="https://..."             # optional

# LOG_FORMAT=                           # optional
# COOLING_DURATION=50ms                 # default: 50ms
# QUERY_TIMEOUT=10s                     # default: 10s
# MAX_CONCURRENT_REQUESTS=50            # default: 50
# POLLING_INTERVAL=3s                   # default: 3s

# Cache Configuration
# CACHE_SIZE=1000                       # default: 1000
# CACHE_TTL=10m                         # default: 10m
# ACCOUNT_CACHE_SIZE=40960              # default: 40960
# NFT_CACHE_SIZE=40960                  # default: 40960
# MSG_TYPE_CACHE_SIZE=1024              # default: 1024
# TYPE_TAG_CACHE_SIZE=1024              # default: 1024
# EVM_TX_HASH_CACHE_SIZE=40960          # default: 40960

# Internal Transaction Configuration
{{if eq (.VMType | lower) "evm"}}INTERNAL_TX=true{{else}}INTERNAL_TX=false{{end}}                       # default: false
# INTERNAL_TX_POLL_INTERVAL=5s          # default: 5s
INTERNAL_TX_BATCH_SIZE=20              # default: 10

# Metrics Configuration
# METRICS_ENABLED=false                 # default: false
# METRICS_PATH=/metrics                 # default: /metrics
# METRICS_PORT=9090                     # default: 9090
`

	// Determine VM type from minitia config if available
	// VM type might be stored in artifacts or inferred from context
	vmType := state.vmType
	// Get JSON RPC URL - for EVM chains, convert RPC port 26657 to JSON RPC port 8545

	data := RollyticsData{
		ChainID: state.chainId,
		VMType:  vmType,
	}

	// Parse the template with custom functions
	tmpl, err := template.New("rollyticsConfig").Funcs(template.FuncMap{
		"lower": strings.ToLower,
	}).Parse(configTemplate)
	if err != nil {
		return err
	}

	homeDir, _ := os.UserHomeDir()
	outputPath := filepath.Join(homeDir, common.RollyticsConfigPath)

	// Ensure the directory exists
	err = os.MkdirAll(filepath.Dir(outputPath), 0o755) // Creates ~/.rollytics if it doesn't exist
	if err != nil {
		return err
	}

	// Open the file for writing
	outputFile, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer outputFile.Close()

	// Execute the template with data
	err = tmpl.Execute(outputFile, data)
	if err != nil {
		return err
	}

	return nil
}
